build: integrated workflow

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -4,6 +4,8 @@ on:
   push:
     branches:
       - "**"
+    tags:
+      - "*"
     paths-ignore:
       - "**/*.md"
   pull_request:
@@ -35,97 +37,84 @@ jobs:
           - name: linux-32-bit
             host: i686-pc-linux-gnu
             os: ubuntu-22.04
-            packages: "gcc-12 g++-12 gcc-12-multilib g++-12-multilib"
+            packages: "gcc-12 g++-12 gcc-12-multilib g++-12-multilib binutils"
             check-security: false
             check-symbols: false
             dep-opts: ""
-            config-opts: "--enable-glibc-back-compat LDFLAGS=-static-libstdc++"
-            goal: install
+            config-opts: "LDFLAGS=-static-libstdc++"
+            goal: install-strip
 
           - name: linux-64-bit
             host: x86_64-pc-linux-gnu
             os: ubuntu-22.04
-            packages: "gcc-12 g++-12"
+            packages: "gcc-12 g++-12 binutils"
             check-security: false
             check-symbols: false
             dep-opts: ""
-            config-opts: "--enable-sse2 --enable-glibc-back-compat LDFLAGS=-static-libstdc++"
-            goal: install
+            config-opts: "--enable-sse2 LDFLAGS=-static-libstdc++"
+            goal: install-strip
 
           - name: windows-64-bit
             host: x86_64-w64-mingw32
-            arch: "i386"
             os: ubuntu-24.04
-            packages: nsis g++-mingw-w64-x86-64-posix wine-binfmt wine64 wine32
-            postinstall: |
-              sudo update-alternatives --set x86_64-w64-mingw32-gcc /usr/bin/x86_64-w64-mingw32-gcc-posix
-              sudo update-alternatives --set x86_64-w64-mingw32-g++ /usr/bin/x86_64-w64-mingw32-g++-posix
-              sudo update-binfmts --import /usr/share/binfmts/wine
+            packages: nsis g++-mingw-w64-x86-64-posix
             check-security: false
             check-symbols: false
             dep-opts: ""
             config-opts: "--enable-sse2 LDFLAGS=-static-libgcc"
-            goal: install
+            goal: install-strip deploy
 
           - name: macos-64-bit
             host: x86_64-apple-darwin
             os: ubuntu-24.04
-            packages: clang lld llvm g++ zip libz-dev python3-setuptools libtinfo6 xorriso
+            packages: clang lld llvm g++ zip
             check-security: false
             check-symbols: false
             dep-opts: ""
             config-opts: "--enable-sse2"
-            goal: deploy
+            goal: install-strip deploy
             sdk: 15.0-15A240d
 
           - name: macos-arm-64-bit
             host: arm64-apple-darwin
             os: ubuntu-24.04
-            packages: clang lld llvm g++ zip libz-dev python3-setuptools libtinfo6 xorriso
+            packages: clang lld llvm g++ zip
             check-security: false
             check-symbols: false
             dep-opts: ""
             config-opts: ""
-            goal: deploy
+            goal: install-strip deploy
             sdk: 15.0-15A240d
 
           - name: linux-arm-32-bit
             host: arm-linux-gnueabihf
             os: ubuntu-22.04
-            packages: "gcc-12-arm-linux-gnueabihf g++-12-arm-linux-gnueabihf binutils-arm-linux-gnueabihf"
+            packages: "gcc-12 g++-12 gcc-12-arm-linux-gnueabihf g++-12-arm-linux-gnueabihf binutils-arm-linux-gnueabihf"
             check-security: false
             check-symbols: false
             dep-opts: ""
-            config-opts: "--enable-glibc-back-compat LDFLAGS=-static-libstdc++"
-            goal: install
+            config-opts: "LDFLAGS=-static-libstdc++"
+            goal: install-strip
 
           - name: linux-arm-64-bit
             host: aarch64-linux-gnu
             os: ubuntu-22.04
-            packages: "gcc-12-aarch64-linux-gnu g++-12-aarch64-linux-gnu binutils-aarch64-linux-gnu"
+            packages: "gcc-12 g++-12 gcc-12 g++-12 gcc-12-aarch64-linux-gnu g++-12-aarch64-linux-gnu binutils-aarch64-linux-gnu"
             check-security: false
             check-symbols: false
             dep-opts: ""
-            config-opts: "--enable-glibc-back-compat LDFLAGS=-static-libstdc++"
-            goal: install
+            config-opts: "LDFLAGS=-static-libstdc++"
+            goal: install-strip
 
     runs-on: ${{ matrix.os }}
 
     steps:
-      - name: Add architecture
-        if: ${{ matrix.arch }}
-        run: |
-          sudo dpkg --add-architecture "${{ matrix.arch }}"
-          sudo rm -f /etc/apt/sources.list.d/microsoft-prod.list
-          sudo apt-get update -qq
-          sudo apt-get remove -qq libmono* moby* mono* nginx* php* libgdiplus libpcre2-posix3 libzip4
-
       - name: Install packages
         run: |
           sudo apt-get update
           sudo apt-get install -y \
-            make automake cmake curl g++-multilib libtool binutils-gold \
-            bsdmainutils pkg-config python3 patch bison xz-utils git build-essential autotools-dev
+            build-essential libtool autotools-dev automake pkg-config \
+            bsdmainutils cmake curl git make patch python3 xz-utils bison
           sudo apt-get install -y ${{ matrix.packages }}
 
       - name: Set gcc-12 as default (native x86)
@@ -168,11 +157,11 @@ jobs:
           aarch64-linux-gnu-gcc --version
 
       - name: Checkout
-        uses: actions/checkout@v7
+        uses: actions/checkout@v7.0.1
 
       - name: SDK cache
         if: ${{ matrix.sdk }}
-        uses: actions/cache@v6
+        uses: actions/cache@v6.1.0
         env:
           cache-name: sdk
         with:
@@ -188,7 +177,7 @@ jobs:
           tar -C depends/SDKs -xzvf depends/sdk-sources/Xcode-${{ matrix.sdk }}-extracted-SDK-with-libcxx-headers.tar.gz
 
       - name: Dependency cache
-        uses: actions/cache@v6
+        uses: actions/cache@v6.1.0
         env:
           cache-name: depends
         with:
@@ -203,8 +192,10 @@ jobs:
       - name: Build Blackcoin More
         run: |
           ./autogen.sh
-          ./configure --prefix=`pwd`/depends/${{ matrix.host }} ${{ matrix.config-opts }} --enable-reduce-exports || ( cat config.log && false)
-          make -j $MAKEJOBS ${{ matrix.goal }} || ( echo "Build failure. Verbose build follows." && make ${{ matrix.goal }} V=1 ; false )
+          CONFIG_SITE=$PWD/depends/${{ matrix.host }}/share/config.site ./configure --prefix=`pwd`/depends/${{ matrix.host }} ${{ matrix.config-opts }} --enable-reduce-exports || ( cat config.log && false)
+          for goal in ${{ matrix.goal }}; do
+            make -j $MAKEJOBS "$goal" || { echo "Build failure. Verbose build follows."; make "$goal" V=1; false; }
+          done
 
       - name: Check security
         if: ${{ matrix.check-security }}
@@ -215,16 +206,74 @@ jobs:
         run: make -C src check-symbols
 
       - name: Upload artifacts
-        uses: actions/upload-artifact@v7
+        uses: actions/upload-artifact@v7.0.1
         with:
           name: blackmore-${{ github.sha }}-${{ matrix.name }}
           path: |
-            depends/${{ matrix.host }}/bin/blackmore*
+            depends/${{ matrix.host }}/bin/*blackmore*
             dist/Blackmore-Qt.app
+            blackcoin-*-win64-setup.exe
           if-no-files-found: error
           retention-days: 7
 
       - name: Download artifacts
-        uses: actions/download-artifact@v8
+        uses: actions/download-artifact@v8.0.1
         with:
           name: blackmore-${{ github.sha }}-${{ matrix.name }}
+
+  docker-publish:
+    name: Build & Push Docker Images
+    needs: build
+    runs-on: ubuntu-22.04
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v7.0.1
+
+      - name: Download AMD64 Artifacts
+        uses: actions/download-artifact@v8.0.1
+        with:
+          name: blackmore-${{ github.sha }}-linux-64-bit
+          path: bin/amd64
+
+      - name: Download ARM64 Artifacts
+        uses: actions/download-artifact@v8.0.1
+        with:
+          name: blackmore-${{ github.sha }}-linux-arm-64-bit
+          path: bin/arm64
+
+      - name: Flatten Artifact Paths
+        run: |
+          find bin/amd64 -type f -name "*blackmore*" -exec cp {} bin/amd64/ \;
+          find bin/arm64 -type f -name "*blackmore*" -exec cp {} bin/arm64/ \;
+          chmod +x bin/amd64/*blackmore*
+          chmod +x bin/arm64/*blackmore*
+
+      - name: Set up QEMU
+        uses: docker/setup-qemu-action@v4.2.0
+
+      - name: Set up Docker Buildx
+        uses: docker/setup-buildx-action@v4.2.0
+
+      - name: Login to DockerHub
+        uses: docker/login-action@v4.6.0
+        with:
+          username: ${{ secrets.DOCKER_USERNAME }}
+          password: ${{ secrets.DOCKER_PASSWORD }}
+
+      - name: Build and push debian multi-arch image
+        uses: docker/build-push-action@v7.3.0
+        with:
+          context: .
+          file: ./Dockerfile.release
+          platforms: linux/amd64,linux/arm64
+          push: true
+          tags: blackcoindev/blackcoin-more-28.4.0-debian:${{ github.ref_name }}
+
+      - name: Build and push minimal multi-arch image
+        uses: docker/build-push-action@v7.3.0
+        with:
+          context: .
+          file: ./Dockerfile.minimal.release
+          platforms: linux/amd64,linux/arm64
+          push: true
+          tags: blackcoindev/blackcoin-more-28.4.0-minimal:${{ github.ref_name }}
